---
- name: Add key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Add PostgreSQL repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    # Default:
    #update_cache: yes

- name: Install dependencies and package
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - python-psycopg2
    - postgresql-9.6-postgis-2.3
    - ptop
    - pgtop

