---
# @ToDo: Split-off Debian-specific parts
- name: Install nginx
  apt: name=nginx state=present

- name: Install certbot's nginx plugin (Debian 8 or 9)
  apt:
    name: python-certbot-nginx
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
  when: (ansible_distribution_major_version == '8') or 
        (ansible_distribution_major_version == '9')

- name: Install certbot's nginx plugin (Debian 10)
  apt: name=python-certbot-nginx state=present
  when: ansible_distribution_major_version == '10'

# @ToDo: Handle Manual SSL certificates
#        (currently we only handle Let's Encrypt free/automatic DV certificates)
# NB Use --staging when developing
- name: Use Certbot to request an SSL certificate (Prod)
  command: certbot --nginx -n --agree-tos --email webmaster@{{ sitename }} -d {{ sitename }}
  become: yes

- name: Use Certbot to request an SSL certificate (post-Prod)
  # We can use the production site's webserver configuration to allow validation
  command: certbot --nginx -n --expand -d {{ all_sites }}
  become: yes
  when: type != 'prod'
  tags:
    - test
    - demo
    - setup

- name: Deleting default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Cross-instance Configuration: gzip_vary
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '# gzip_vary on;'
    replace: 'gzip_vary on;'
  become: yes

- name: Cross-instance Configuration: gzip_proxied
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '# gzip_proxied any;'
    replace: 'gzip_proxied expired no-cache no-store private auth;'
  become: yes

- name: Cross-instance Configuration: gzip_types
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;'
    replace: 'gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;'
  become: yes

- name: Cross-instance Configuration: gzip_min_length
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: '^\sgzip_proxied'
    line: '\tgzip_min_length 10240;'
  become: yes

- name: Creating instance configuration
  template: src=conf.j2 dest=/etc/nginx/sites-enabled/{{ type }}.conf
  tags:
    - test
    - demo
    - setup

- name: Restart nginx
  service: name=nginx state=restarted
  tags:
    - test
    - demo
    - setup
