---
- name: Download & Unzip
  unarchive:
    src: http://projects.unbit.it/downloads/uwsgi-1.9.18.2.tar.gz
    dest: /tmp
    remote_src: yes

- name: Build
  shell: "{{ item }} chdir=/tmp/uwsgi-1.9.18.2"
  with_items:
    - python uwsgiconfig.py --build pyonly.ini
    - cp uwsgi /usr/local/bin

- name: Copy Files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'logrotate', dest: '/etc/logrotate.d/uwsgi' }
    - { src: 'scheduler', dest: '/home/{{ type }}/run_scheduler.py' }
  tags:
    - test
    - demo

- name: uwsgi.ini
  template: src='uwsgi.ini.j2' dest='/home/{{ type }}/uwsgi.ini'
  tags:
    - test
    - demo

- name: service script
  template: src='uwsgi.j2' dest='/etc/init.d/uwsgi-{{ type }}'
  tags:
    - test
    - demo

- name: Create pid file
  file: path=/tmp/uwsgi-{{ type }}.pid state=touch owner=web2py group=web2py
  tags:
    - test
    - demo

- name: Create log dir
  file: path=/var/log/uwsgi state=directory owner=web2py group=web2py

- name: Fix permissions for init.d script
  file: path=/etc/init.d/uwsgi-{{ type }} state=file mode=755
  tags:
    - test
    - demo

- name: update-rc.d
  command: update-rc.d uwsgi-{{ type }} defaults
  tags:
    - test
    - demo