---
- name: Download & Unzip
  unarchive:
    src: https://projects.unbit.it/downloads/uwsgi-2.0.20.tar.gz
    dest: /tmp
    remote_src: yes

- name: Build
  command: python uwsgiconfig.py --build pyonly chdir=/tmp/uwsgi-2.0.20

- name: Copy uwsgi bin
  copy:
    src: /tmp/uwsgi-2.0.20/uwsgi
    dest: /usr/local/bin/uwsgi
    mode: 0755
    remote_src: yes
  become: yes

- name: Copy logrotate File
  copy: src='logrotate' dest='/etc/logrotate.d/uwsgi'
  become: yes

#- name: Create directeory for init support files
#  file:
#    path: /usr/share/uwsgi/init
#    state: directory
#    recurse: yes
#  become: yes

#- name: Copy init files
#  copy: src="{{ item.src }}" dest="{{ item.dest }}"
#  loop:
#    - { src: 'uwsgi.init.d', dest: '/etc/init.d/uwsgi' }
#    - { src: 'do_command', dest: '/usr/share/uwsgi/init/do_command' }
#    - { src: 'snippets', dest: '/usr/share/uwsgi/init/snippets' }
#    - { src: 'specific_daemon', dest: '/usr/share/uwsgi/init/specific_daemon' }
#  become: yes

#- name: Create directory for config files
#  file:
#    path: /etc/uwsgi/apps-enabled
#    state: directory
#    recurse: yes
#  become: yes

- name: Copy Templates
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  loop:
    - { src: 'scheduler.j2', dest: '/home/{{ type }}/run_scheduler.py' }
    #- { src: 'uwsgi.ini.j2', dest: '/etc/uwsgi/apps-enabled/{{ type }}.ini' }
    - { src: 'uwsgi.ini.j2', dest: '/home/{{ type }}/uwsgi.ini' }
    #- { src: 'uwsgi.j2', dest: '/etc/init.d/uwsgi-{{ type }}' }
    - { src: 'uwsgi-core.init.d.custom.j2', dest: '/etc/init.d/uwsgi-{{ type }}' }
  become: yes
  tags:
    - test
    - demo
    - setup

- name: Fix permissions for init.d script
  file: path=/etc/init.d/uwsgi-{{ type }} state=file mode=755
  #file: path=/etc/init.d/uwsgi state=file mode=755
  become: yes
  tags:
    - test
    - demo
    - setup

# Done automatically by init script as-required:
#- name: Create pid folder
#  file: path=/var/run/uwsgi state=directory owner=web2py group=web2py
#  become: yes

#- name: Create pid file
#  file: path=/var/run/uwsgi/uwsgi-{{ type }}.pid state=touch owner=web2py group=web2py
#  become: yes
#  tags:
#    - test
#    - demo
#    - setup

- name: Create log dir
  file:
    path: /var/log/uwsgi
    state: directory
    owner: web2py
    group: web2py
  become: yes

# Add Boot Startup Files
- name: update-rc.d
  command: update-rc.d uwsgi-{{ type }} {{item}}
  become: yes
  loop:
    - remove
    - defaults
  tags:
    - test
    - demo
    - setup

- name: update-rc.d
  command: update-rc.d uwsgi-{{ type }} {{item}}
  become: yes
  when: start != True
  loop:
  - disable 2
  - disable 3
  - disable 4
  - disable 5
  tags:
    - test
    - demo
    - setup
