- name: create swap file
  command: fallocate -l {{ swap_space }} {{ swap_file }}

- name: set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: format swap file
  command: mkswap {{ swap_file }}

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: turn on swap
  command: swapon -a

# https://en.wikipedia.org/wiki/Swappiness
- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
