---
- name: Run clean script (Test)
  command: clean test
  ignore_errors: yes
  when:
    - type == 'test'
    - db_type == 'postgresql' # MySQL clean script not yet multi-instance
  become: yes
  tags:
    - test

- name: Create Tables & Prepopulate (Prod / Demo / Setup)
  #command: sudo -H -u web2py python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/noop.py
  command: python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/noop.py chdir=/home/{{ type }}
  become: yes
  become_user: web2py
  #become_flags: '-H'
  tags:
    - demo
    - setup

- name: Configure for Production
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^#settings.base.prepopulate = 0', line: 'settings.base.prepopulate = 0' }
    - { regexp: '^settings.base.migrate = True', line: 'settings.base.migrate = False' }
  tags:
    - demo
    - test
    - setup

- name: Compile
  #command: sudo -H -u web2py python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/compile.py chdir=/home/{{ type }}
  command: python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/compile.py chdir=/home/{{ type }}
  become: yes
  become_user: web2py
  #become_flags: '-H'
  notify: Restart Webserver
  tags:
    - demo
    - test
    - setup

- name: Create script to Import Admin User from coapp -> Prod
  template: src="import_admin_user.py.j2" dest="/tmp/import_admin_user.py"
#  tags: # or from Prod -> Co-app
#    - setup

- name: Import Admin User from coapp -> Prod
  #command: sudo -H -u web2py python web2py.py -S {{ appname }} -M -R /tmp/import_admin_user.py chdir=/home/{{ type }}
  command: python web2py.py -S {{ appname }} -M -R /tmp/import_admin_user.py chdir=/home/{{ type }}
  become: yes
  become_user: web2py
  #become_flags: '-H'
#  tags: # or from Prod -> Co-app
#    - setup

# @ToDo: Import Admin User(s) from Prod -> coapp when coapp.stat.exists == False

- name: Stop Rocket Server (if deploying from co-app bootstrap)
  #service: name=web2py  state=stopped
  command: /etc/init.d/web2py stop
  ignore_errors: True

- name: Remove port 80 redirection rule (if deploying from co-app bootstrap)
  command: iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000
  ignore_errors: True

# Shouldn't be required but currently is:
# - to handle cherokee restart
#- name: Reboot
#  command: shutdown -r +1
#  ignore_errors: True
#  become: yes
#  when:
#    - type != 'prod'
#  tags:
#    - demo
#    - test
#    - setup
