---
- name: Install Exim4
  apt:
    name: ['exim4-config',
           'exim4-daemon-light',
           ]
    state: present
  become: yes

- name: Configure for Internet Mail Delivery
  command: dpkg-reconfigure -f noninteractive exim4-config
  become: yes

