---
- name: Install MySQL
  apt:
    name: ['mysql-server',
           'libmysqlclient-dev',
           ]
    state: present
    install_recommends: no
  become: yes

- name: Install MySQL Python Driver (Debian 10)
  apt:
    name: ['python3-mysqldb',
           ]
    state: present
    install_recommends: no
  become: yes
  when: ansible_distribution_major_version == '10'

- name: Install MySQL Python Driver (Debian 7, 8 or 9)
  apt:
    name: ['python-mysqldb',
           ]
    state: present
    install_recommends: no
  become: yes
  when: ansible_distribution_major_version != '10'

- name: Install phpmyadmin
  apt:
    name: ['php5-cgi',
           'php5-mysql',
           'phpmyadmin',
           'mytop',
           ]
    state: present
    install_recommends: no
  become: yes

