---
- name: Create ansible cfg dir
  file: path=/etc/ansible state=directory

- name: Copy ansible.cfg
  copy: src=ansible.cfg dest=/etc/ansible/ansible.cfg

# Not writable by Web2Py user & anyway we have it in syslog
#- name: Create ansible logfile
#  file: path=/var/log/ansible.log state=touch

# http://hakunin.com/six-ansible-practices#add-github-to-knownhosts-properly-and-securely
- name: Ensure github.com is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

# @ToDo: Separate to debian.yml
- name: Uninstall OS' Boto package
  apt:
    name: ['python-boto',
           'python3-boto',
           'python3-botocore',
           ]
    state: absent
    autoremove: yes

- name: Install Boto # Want latest version to know about all regions
  pip: name=boto

- name: Install Boto3
  pip: name=boto3

# Needed for 'dig' lookup
- name: Install DNSPython
  pip: name=dnspython

