---
- name: Create ansible cfg dir
  file: path=/etc/ansible state=directory

- name: Copy ansible.cfg
  copy: src=ansible.cfg dest=/etc/ansible/ansible.cfg

- name: Create ansible logfile
  file: path=/var/log/ansible.log state=touch
