---
# @ToDo: Split-off Debian-specific parts
- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool
    - gettext
    - rrdtool

- name: Install libtool-bin (Debian 8 or 9)
  apt: name=libtool-bin state=latest
  when: ansible_distribution_major_version != '7'

#- name: Clone Repo
#  git: repo=http://github.com/cherokee/webserver.git dest=/tmp/webserver

- name: Download & Unzip
  unarchive:
    src: https://github.com/cherokee/webserver/archive/master.zip
    dest: /tmp
    remote_src: yes

- name: Build
  command: "{{ item }}"
  args:
    #chdir: /tmp/webserver
    chdir: /tmp/webserver-master
  with_items:
    - ./autogen.sh --prefix=/usr --localstatedir=/var --sysconfdir=/etc
    - make
    - make install

- name: Create log dir
  file: path=/var/log/cherokee state=directory owner=www-data group=www-data

- name: Create graphs dir
  file: path=/var/lib/cherokee/graphs state=directory owner=www-data group=www-data

- name: Copy init.d script
  copy: src=cherokee dest=/etc/init.d/cherokee mode=755

- name: update-rc.d
  command: update-rc.d cherokee defaults

- name: Copying cherokee.conf
  template: src=cherokee.conf dest=/etc/cherokee/cherokee.conf
  tags:
    - test
    - demo

- name: Copying update_cherokee.py
  template: src=update_cherokee_{{ type }}.py dest=/tmp/update_cherokee.py
  tags:
    - demo
    - test

- name: Executing update_cherokee
  command: python update_cherokee.py chdir=/tmp/
  tags:
    - test
    - demo

- name: Copy maintenance.html
  copy: src=maintenance.html dest=/var/www/maintenance.html
  tags:
    - test
    - demo

- name: Restart Cherokee
  service: name=cherokee state=restarted
