---
# Check for correct Version
- fail: msg="Exiting as this deployment method currently only supports Debian 7, 8, 9, 10 or 11"
  when:
    - ansible_distribution_major_version != '7'
    - ansible_distribution_major_version != '8'
    - ansible_distribution_major_version != '9'
    - ansible_distribution_major_version != '10'
    - ansible_distribution_major_version != '11'

- name: Set python_major_version variable to 3
  set_fact:
    python_major_version: "3"
  when: (ansible_distribution_major_version == '10') or 
        (ansible_distribution_major_version == '11')
  tags:
    - demo
    - setup
    - test

- name: Set python_major_version variable to 2
  set_fact:
    python_major_version: "2"
  when: (ansible_distribution_major_version == '7') or 
        (ansible_distribution_major_version == '8') or
        (ansible_distribution_major_version == '9')
  tags:
    - demo
    - setup
    - test

- name: Set Python 3 as default
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3.7
  become: yes
  when: ansible_distribution_major_version == '10'

- name: Set Python 3 as default
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3.9
  become: yes
  when: ansible_distribution_major_version == '11'

# Add Backports repo (for Certbot)
- name: Add Backports repo (Debian 8 or 9)
  apt_repository:
    repo: deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
  become: yes
  when: (ansible_distribution_major_version == '8') or 
        (ansible_distribution_major_version == '9')

# Install Admin Tools
# state=present not state=latest as we don't want to upgrade accidentally
- name: Install Admin Tools
  apt:
    name: ['at',
           'curl',
           'dos2unix',
           'htop',
           'lrzsz',
           'mlocate',
           'p7zip',
           'psmisc',
           'rcconf',
           'sudo',
           'telnet',
           'unzip',
           'vim',
           ]
    state: present
    update_cache: yes # update-cache=yes is the equivalent of apt-get update
  become: yes

# Certbot
- name: Install Certbot (Debian 7)
  # https://certbot.eff.org/lets-encrypt/debianwheezy-other
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/bin/certbot
    mode: 0775
  become: yes
  when: ansible_distribution_major_version == '7'

- name: Schedule Certificate renewals (Debian 7)
  copy: src=cron_certbot_renew dest=/etc/cron.d/certbot
  become: yes
  when: ansible_distribution_major_version == '7'

- name: Install Certbot (Debian 8 or 9)
  apt: name=certbot state=present default_release={{ ansible_distribution_release }}-backports
  become: yes
  when: (ansible_distribution_major_version == '8') or 
        (ansible_distribution_major_version == '9')

# Elinks
- name: Install elinks (Debian 9, 10)
  apt: name={{item}} state=present
  become: yes
  when: (ansible_distribution_major_version == '9') or 
        (ansible_distribution_major_version == '10') or 
        (ansible_distribution_major_version == '11')
  loop:
    - elinks
    - net-tools

- name: Install elinks (Debian 7 or 8)
  apt: name=elinks-lite state=present
  become: yes
  when: (ansible_distribution_major_version == '7') or 
        (ansible_distribution_major_version == '8')

# Git
- name: Install git
  apt: name=git-core state=present
  become: yes

# Install Libraries
- name: Install libodbc1 # Needed for Web2Py
  apt: name=libodbc1 state=present
  become: yes

- name: Install libgeos (Debian 9 or 10)
  apt: name=libgeos-c1v5 state=present
  become: yes
  when: (ansible_distribution_major_version == '9') or 
        (ansible_distribution_major_version == '10') or 
        (ansible_distribution_major_version == '11')

- name: Install libgeos (Debian 7 or 8)
  apt: name=libgeos-c1 state=present
  become: yes
  when: (ansible_distribution_major_version == '7') or 
        (ansible_distribution_major_version == '8')

- name: Install python libs (Debian 10)
  apt:
    name: ['python3-dev',
           #'python3-dateutil',
           #'python3-lxml',
           'python3-setuptools',
           'python3-serial',
           #'python3-pil',
           #'python3-reportlab',    # Now using PIP version for Percentage support
           #'python3-matplotlib',   # Only used by deprecated survey module
           #'python3-requests',
           #'python3-xlwt',
           'build-essential',
           'libgeos-dev',
           'python3-pip',
           ]
    state: present
  become: yes
  when: (ansible_distribution_major_version == '10') or 
        (ansible_distribution_major_version == '11')

- name: Install python libs (Debian 7, 8 or 9)
  apt:
    name: ['python-dev',
           #'python-dateutil',
           #'python-lxml',
           'python-setuptools',
           'python-serial',
           #'python-imaging',
           #'python-reportlab',     # Now using PIP version for Percentage support
           #'python-matplotlib',    # Only used by deprecated survey module
           #'python-requests',      # APT package fails to import on Debian 9
           #'python-xlwt',
           'build-essential',
           'libgeos-dev',
           'python-pip',
           ]
    state: present
  become: yes
  when: (ansible_distribution_major_version == '7') or 
        (ansible_distribution_major_version == '8') or
        (ansible_distribution_major_version == '9')
