---
# Tasks specific to Amazon EC2
- name: Disable update_etc_hosts
  lineinfile: dest=/etc/cloud/cloud.cfg
              regexp="^ - update_etc_hosts"
              insertafter="^ - update_etc_hosts"
              line="# - update_etc_hosts"
              state=present
  #when: cloud_cfg.stat.exists

- name: Disable update_hostname
  lineinfile: dest=/etc/cloud/cloud.cfg
              regexp="^ - update_hostname"
              insertafter="^ - update_hostname"
              line="# - update_hostname"
              state=present
  #when: cloud_cfg.stat.exists

