---
# Check for correct OS
-  fail: msg="Exiting as this deployment method currently only supports Debian"
   when: ansible_distribution != "Debian" # Doesn't include Ubuntu (ansible_os_family does))

- name: check if we're running on EC2
  stat:
    path: "/etc/cloud/cloud.cfg"
    get_attributes: False
    get_checksum:   False
    get_md5:        False
    get_mime:       False
  register: cloud_cfg

- name: Disable update_etc_hosts
  lineinfile: dest=/etc/cloud/cloud.cfg
              regexp="^ - update_etc_hosts"
              insertafter="^ - update_etc_hosts"
              line="# - update_etc_hosts"
              state=present
  when: cloud_cfg.stat.exists

- name: Disable update_hostname
  lineinfile: dest=/etc/cloud/cloud.cfg
              regexp="^ - update_hostname"
              insertafter="^ - update_hostname"
              line="# - update_hostname"
              state=present
  when: cloud_cfg.stat.exists

- name: Update hostname file
  template: src=hostname dest=/etc/hostname

- name: Update hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127.0.0.1 localhost"
              insertafter="^127.0.0.1 localhost"
              line="127.0.0.1 {{ sitename }} {{ hostname }} localhost"
              state=present

- name: Update mailname file
  template: src=mailname dest=/etc/mailname

# Run Debian-specific tasks
-  import_tasks: debian.yml
   when: ansible_distribution == "Debian" # Doesn't include Ubuntu (ansible_os_family does))

# Python Libraries, where we need a more recent version than that provided by the OS
- name: Install Reportlab # Want Percentage support
  pip: name=reportlab

- name: Install Shapely # Want Simplify enhancements
  pip: name=Shapely

- name: Install XLRD # XLS import support
  pip: name=xlrd

# Web2Py
- name: Create web2py user
  #user: name=web2py system=true
  command: adduser --system --disabled-password web2py

- name: Create web2py group
  group: name=web2py state=present

- name: Create symlink
  file: src=/home/web2py dest=/home/prod state=link owner=web2py group=web2py

- name: Clone web2py # recursive by default
  git: repo=git://github.com/web2py/web2py.git dest=/home/{{ type}} version=cda35fd
  tags:
    - test
    - demo
    - setup

# 2.14.6
#- name: Checkout stable release of Web2Py
#  command: git reset --hard cda35fd
#  args:
#    chdir: /home/{{ type }}
#  tags:
#    - test
#    - demo
#    - setup

- name: Configure PyDAL
  command: git submodule update --init --recursive
  args:
    chdir: /home/{{ type }}
  tags:
    - test
    - demo
    - setup

- name: Copy wsgihandler
  command: cp -f /home/{{ type }}/handlers/wsgihandler.py /home/{{ type }}
  tags:
    - test
    - demo
    - setup

- name: Copy routes.py
  template: src=routes.py dest=/home/{{ type }}/routes.py
  tags:
    - test
    - demo
    - setup

# matplotlib
# Only used by deprecated survey module
#- name: Create matplotlib directory
#  file: path=/home/{{ type }}/.matplotlib state=directory owner=web2py

#- name: Update wsgihandler.py
#  lineinfile: dest=/home/{{ type }}/wsgihandler.py
#              regexp=''
#              insertafter=EOF
#              line='os.environ["MPLCONFIGDIR"] = "/home/{{ type }}/.matplotlib"'

# - name: Edit matplotlibrc
#   lineinfile: dest=/etc/matplotlibrc state=present backref=yes regexp='backend      : TkAgg' line='backend      : Agg'

- name: Create symlink
  file: src=/home/{{ type }} dest=/root/{{ type }} state=link
  tags:
    - test
    - demo
    - setup

# Eden
- name: Clone Eden # recursive by default
  git: repo=git://github.com/sahana/eden.git dest=/home/{{ type }}/applications/{{ appname }}
  tags:
    - test
    - demo
    - setup

- name: Fix permissions
  file: path=/home/{{item}} state=directory owner=web2py
  with_items:
    - "{{ type }}/applications"
    - "{{ type }}/applications/admin/cache"
    - "{{ type }}/applications/admin/cron"
    - "{{ type }}/applications/admin/databases"
    - "{{ type }}/applications/admin/errors"
    - "{{ type }}/applications/admin/sessions"
    - "{{ type }}/applications/{{ appname }}"
    - "{{ type }}/applications/{{ appname }}/cache"
    - "{{ type }}/applications/{{ appname }}/cron"
    - "{{ type }}/applications/{{ appname }}/databases"
    - "{{ type }}/applications/{{ appname }}/errors"
    - "{{ type }}/applications/{{ appname }}/models"
    - "{{ type }}/applications/{{ appname }}/sessions"
    - "{{ type }}/applications/{{ appname }}/static/cache"
    - "{{ type }}/applications/{{ appname }}/static/cache/chart"
    - "{{ type }}/applications/{{ appname }}/static/fonts"
    - "{{ type }}/applications/{{ appname }}/static/img/markers"
    - "{{ type }}/applications/{{ appname }}/uploads"
    - "{{ type }}/applications/{{ appname }}/uploads/gis_cache"
    - "{{ type }}/applications/{{ appname }}/uploads/images"
    - "{{ type }}/applications/{{ appname }}/uploads/tracks"
  tags:
    - test
    - demo
    - setup

- name: Fix permissions
  file: path=/home/web2py state=directory owner=web2py
  when: type == 'prod'

- name: Fix permissions
  file: path="/home/{{ type }}" state=directory owner=web2py
  when: type != 'prod'
  tags:
    - test
    - demo
    - setup

- name: Create symlink (eden in web2py)
  file: src=/home/{{ type }}/applications/{{ appname }} dest=/home/{{ type }}/eden state=link
  tags:
    - test
    - demo
    - setup

- name: Create symlink (eden in home)
  file: src=/home/{{ type }}/applications/{{ appname }} dest=/root/eden state=link

- name: Update crontab
  copy: src=cron dest=/etc/crontab

- stat: path=/home/setup/applications/eden/models/000_config.py
  register: setup
  
- name: Copy read_hmac_key.py
  copy: "src=read_hmac_key.py dest=/tmp/read_hmac_key.py"
  when: setup.stat.exists == True

- name: Read hmac_key from Setup for Prod
  command: python web2py.py -S {{ appname }} -M -R /tmp/read_hmac_key.py chdir=/home/{{ type }}
  become: true
  become_user: web2py
  #become_flags: '-H'
  ignore_errors: yes
  when: setup.stat.exists == True

- name: Set hmac_key variable
  set_fact:
    hmac_key: "{{ lookup('file', '/tmp/hmac_key') }}"
  when: setup.stat.exists == True

- name: Generate & set hmac_key variable
  set_fact:
    hmac_key: "{{ lookup('password', '/tmp/hmac_key chars=ascii_letters,digits,.-_,,') }}" # Cannot include : or "
  when: (type == 'prod' and setup.stat.exists == False) or 
        (type != 'prod')
  tags:
    - demo
    - setup

- name: Remove hmac_key file
  file: path=/tmp/hmac_key state=absent
  tags:
    - demo
    - setup

- name: Copying default 000_config.py
  copy: src=/home/{{ type }}/applications/{{ appname }}/modules/templates/000_config.py dest=/home/{{ type }}/applications/{{ appname }}/models
  remote_src: yes
  tags:
    - demo
    - setup

- name: Copying 000_config.py from Production for Test (need same HMAC for passwords and settings should match)
  # Assumes that appname for Prod is the same as Test!
  copy: src=/home/prod/applications/{{ appname }}/models/000_config.py dest=/home/{{ type }}/applications/{{ appname }}/models
  remote_src: yes
  when: type == 'test'
  tags:
    - test

- name: Editing 000_config.py (Prod / Demo / Setup)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^FINISHED_EDITING_CONFIG_FILE = False', line: 'FINISHED_EDITING_CONFIG_FILE = True' }
    - { regexp: 'akeytochange', line: 'settings.auth.hmac_key = "{{ hmac_key }}"' }
    - { regexp: '^#settings.base.public_url = \"http://127.0.0.1:8000\"', line: 'settings.base.public_url = "{{ protocol }}://{{ sitename }}"' }
    - { regexp: '^#settings.base.cdn = True', line: 'settings.base.cdn = True' }
  tags:
    - demo
    - setup

- name: Editing 000_config.py (Prod / Setup)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^#settings.base.prepopulate_demo = 0'
              backrefs=yes
              line='settings.base.prepopulate_demo = 0'
              state=present
  tags:
    - setup
    
- name: Editing 000_config.py (Test)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^#settings.base.public_url = \"http://127.0.0.1:8000\"'
              backrefs=yes
              line='settings.base.public_url = "{{ protocol }}://{{ sitename }}"'
              state=present

- name: set template_type variable
  set_fact:
    template_type: "{{ template | type_debug }}"

# Coming from Setup module
- name: Setting Templates (Prod / Demo)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^settings.base.template = \"default\"'
              backrefs=yes
              line='settings.base.template = ["{{ template | join('", "') }}"]'
              state=present
  when:
    - template_type == 'list'
  tags:
    - demo

# Coming from bootstrap
- name: Setting Template (Prod / Demo)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^settings.base.template = \"default\"'
              backrefs=yes
              line='settings.base.template = "{{ template }}"'
              state=present
  when:
    - template_type == 'AnsibleUnicode'
  tags:
    - demo

- name: Setting Template (Setup)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^settings.base.template = \"default\"'
              backrefs=yes
              line='settings.base.template = "setup"'
              state=present
  when:
    - type != 'prod'
  tags:
    - setup

- name: Setting Sender (Prod)
  lineinfile: dest=/home/{{ type }}/applications/{{ appname }}/models/000_config.py
              regexp='^#settings.mail.sender = \"'Sahana' <sahana@example.org>\"'
              backrefs=yes
              line='settings.mail.sender = "<{{ sender }}>"'
              state=present
  when: not((sender is undefined) or (sender is none) or (sender|trim == ''))

# NB These are all designed for a single-host setup
# @ToDo: Replace with Ansible methods which are multi-host aware
- name: Copy management scripts
  copy: "src={{ item.src }} dest={{ item.dest }} mode=755"
  with_items:
    - { src: 'compile', dest: '/usr/local/bin/compile' }
    - { src: 'pull', dest: '/usr/local/bin/pull' }
    - { src: 'revert', dest: '/usr/local/bin/revert' }
    - { src: 'w2p', dest: '/usr/local/bin/w2p' }
